### ISSUE TITLE
Missing C++ version of Palindrome Number Check

### ISSUE THREAD

**Issue by Kushal-Agrawal-11** [NiharRanjan53/HacktoberFest_2022#65]
There should be a program to check whether the given number is a palindrome or not.

**Comment by nisthajnn** [comment]
please assign this to me

**Comment by Shinchan2803** [comment]
can u assign to me this problem

**Comment by Utkarsh2312** [comment]
Hello,
I am a competitive programming Enthusiast(3⭐ at Codechef) and I would like to contribute in your repository. Can you please, assign this task to me.
