### ISSUE TITLE
Comment box

### ISSUE THREAD

**Issue by AryanSahoo-2003** [NiharRanjan53/HacktoberFest_2022#91]
I want to add comment box basic made using php and html so as to make others to dive how to use it as well as to show it simplicity

**Comment by Utkarsh2312** [comment]
I would like to solve this task. Can you, please assign this task to me.

**Comment by AryanSahoo-2003** [comment]
Yes! I would love to assign it to you :) Reply me back

**Comment by Utkarsh2312** [comment]
Yeah please assign me this task. I can assure you that you will not be disappointed and this task also help me for contributing my first task in Hacktober Fest.

**Comment by Utkarsh2312** [comment]
Please assign it to me under Hacktober Fest 2022

**Comment by AryanSahoo-2003** [comment]
you can start working on it as soon as possible,I will do it at time of merging:)

**Comment by Utkarsh2312** [comment]
okay, fine but please don't forget about it.

**Comment by Utkarsh2312** [comment]
Actually for saving comments we have to use MySQL. Will that be okay?

**Comment by AryanSahoo-2003** [comment]
Yeah yeah you can do that!or simply make it using a seperate comment . TXT file

**Comment by AryanSahoo-2003** [comment]
I will tell the author about you and he will validate... but i think you should go for other repo as this repo's author is not active for about 2-3 days

**Comment by AryanSahoo-2003** [comment]
I can recommend you to other repo instead tho..if you want that..

**Comment by Utkarsh2312** [comment]
Yeah sure !
And also I have already created the pull request for the task you can check. Please merge it with the label of Hacktober Fest 2022 so that my contribution also added to Hacktober Fest 2022.

**Comment by Utkarsh2312** [comment]
Please merge my pull request. It has been 2 days already

**Comment by AryanSahoo-2003** [comment]
> Please merge my pull request. It has been 2 days already

Actually this repo has been excluded as author said he will not be merging any PR

You can do other PR on paryanta, Anisha etc
Happy contribution!
